---
galaxy_info:
  author: Eden Sitkovetsky
  description: Role to manage users on remote servers, allowing you to add new users and remove unwanted ones.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
