---
- name: Install Apache on Debian
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install Apache on RedHat
  yum:
    name: httpd
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Update Apache port
  lineinfile:
    path: "{{ '/etc/apache2/ports.conf' if ansible_facts['os_family'] == 'Debian' else '/etc/httpd/conf/httpd.conf' }}"
    regexp: '^Listen'
    line: "Listen {{ apache_port }}"

- name: Restart Apache
  service:
    name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
    state: restarted
    enabled: yes
