---
- name: Install Python3, pip, and venv
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-venv

- name: Create project directory
  file:
    path: /home/ubuntu/flaskapp
    state: directory
    mode: '0755'

- name: Create virtual environment
  command: python3 -m venv /home/ubuntu/flaskapp/venv
  args:
    creates: /home/ubuntu/flaskapp/venv/bin/activate

- name: Install Flask in virtual environment
  command: /home/ubuntu/flaskapp/venv/bin/pip install flask

- name: Create Flask application
  copy:
    dest: /home/ubuntu/flaskapp/app.py
    content: |
      from flask import Flask
      app = Flask(__name__)
      @app.route("/")
      def hello():
          return "Hello from Flask !"
      if __name__ == "__main__":
          app.run(host="0.0.0.0", port={{ flask_port }})

- name: Run Flask in background
  shell: |
    nohup /home/ubuntu/flaskapp/venv/bin/python /home/ubuntu/flaskapp/app.py &
