---
- name: Install MySQL (Debian)
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install MySQL (RedHat)
  yum:
    name: mysql-server
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Start and enable MySQL
  service:
    name: "{{ 'mysql' if ansible_facts['os_family'] == 'Debian' else 'mysqld' }}"
    state: started
    enabled: yes
