---
- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: yes

- name: Run Node Exporter with custom port
  shell: |
    nohup /opt/node_exporter-1.7.0.linux-amd64/node_exporter --web.listen-address=":{{ node_exporter_port }}" &
